---
title: "Project proposal"
author: "Reiner, Oysik, Solomon, Sam & Linn"
date: "2024-07-01"
output: html_document
---
# Introduction
- give our problem statement
- state our goals for the report
- introduce bed nets, more specfically LLINs and define issues
- mention BOHEMIA's interest in bed nets as a way to prevent childhood malaria 

# Bed Nets
- tabulate price in a five number summary 
- tabulate # per household in five number summary 
- stretch goal: most common source of bed nets

# Ownership, Sufficiency, and Usage
Within this section, we will have subsections going over each portion of our analysis:

## Relationship between ownership, sufficiency, and usage
### Safety
- household data for each attribute over three months 
- bar graphs for visit V1 through V4 with all three attributes
- tabulate data for each attribute in five number summary

### Efficacy
- children ages 5-15 data for each attribute over six months
- bar graphs for visit V1 through V7 with all three attributes
- tabulate data for each attribute in five number summary

## Differences in usage between V1 through V7 within the efficacy cohort
- box plot of efficacy usage data by visit
- discussion of statistical findings (null hypothesis)

## Effects of environmental factors on bed net usage
- scatter plot of efficacy data, faceted by visit
- x = average temperature (of previous month), y = % usage, points = villages
- discussion of findings 

## Effects of community usage on malaria incidence 
- scatter plot of safety data, averaging visits into total % usage
- x = malaria incidence, y = % usage, points = villages
- discussion of findings

## Possible auto correlations
### Safety
- household data over three months 
- tabulate data showing net usage and changes over time

### Efficacy
- children ages 5-15 data over six months
- tabulate data showing net usage and changes over time

